# -*- coding: utf-8 -*-
"""dataloader_od.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rfFZgoOQGKjTTUXSgcgzHRsNRDCWS4yF
"""

git clone https://github.com/EscVM/OIDv4_ToolKit.git
pip3 install -r /content/OIDv4_ToolKit/requirements.txt
python3 /content/OIDv4_ToolKit/main.py downloader --classes Bear Person Elephant Tree Tiger --type_csv train --limit 400
zip -r /content/Tiger_od.zip /content/OID/Dataset/train/Tiger
zip -r /content/Elephant_od.zip /content/OID/Dataset/train/Elephant
zip -r /content/Tree_od.zip /content/OID/Dataset/train/Tree
zip -r /content/Person_od.zip /content/OID/Dataset/train/Person
zip -r /content/Bear_od.zip /content/OID/Dataset/train/Bear
cp -r /content/Tiger_od.zip --Enter Path--
cp -r /content/Elephant_od.zip --Enter Path--
cp -r /content/Tree_od.zip --Enter Path--
cp -r /content/Person_od.zip --Enter Path--
cp -r /content/Bear_od.zip --Enter Path--